# -*- coding: utf-8 -*-
"""Unemployment_Rate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UhXg9BvdlM8B_PQQN7tjZug_9AIT1iPH

OASIS INFOBYTE DATA SCIENCE INTERNSHIP PROJECT.

Task #3: Analysis of the Unemployment Rate in the India  with Python.

--> Unemployment rate is calculated in particular Region.
"""



#Importing the Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

#Loading the Data 
from google.colab import files
uploaded = files.upload()

#Reading the Data 
data=pd.read_csv("/content/Unemployment in India.csv")
data=pd.read_csv("/content/Unemployment_Rate_upto_11_2020.csv")
print(data.head())

#Checking for the Null Values.
print(data.isnull().sum())

#Renaming the Data columns for better Analysis
data.columns = ["States","Date","Frequency","Estimated Unemployment Rate", "Estimated Employed",
                "Estimated Labour Participation Rate","Region","longitude","latitude"]

#Correlation
plt.style.use('seaborn-whitegrid')
plt.figure(figsize = (12,10))
sns.heatmap(data.corr())
plt.show()

#Data Visualization
# Estimating the Employment Rate according to the different "Region" of the India.
data.columns = ["States","Date","Frequency",
                "Estimated Unemployment Rate", 
                "Estimated Employed",
                "Estimated Labour participation rate",
                "Region","longitude","latitude"]
plt.title("Indian Unemployment")
sns.histplot(x="Estimated Employed", hue= "Region", data =data)
plt.show()

# Estimating the Uemployment Rate according to the different "Region" of the India.
plt.figure(figsize=(12,10))
plt.title("Indian Unemployment")
sns.histplot(x="Estimated Unemployment Rate", hue="Region", data =data)
plt.show()

#Creating the Dashboard, showing the Indivisual unemployment Rate in Stateswise.
umemploment = data[["States","Region","Estimated Unemployment Rate"]]
figure = px.sunburst(umemploment,path=["Region","States"],values="Estimated Unemployment Rate", width=700, height=700,
color_continuous_scale="RdY1Gn", title="Unemployment Rate in India")
figure.show()

